# Generated by Django 5.2.17 on 2026-08-15 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('public', '公开展示'), ('private', '敏感资料')], max_length=16)),
                ('category', models.CharField(choices=[('avatar', '用户头像'), ('provider_photo', '达人展示照片'), ('certification', '资质材料'), ('identity', '实名认证材料'), ('activity_cover', '活动封面'), ('review_image', '评价图片'), ('order_evidence', '履约证据'), ('support_attachment', '客服附件'), ('other', '其他')], max_length=32)),
                ('status', models.CharField(choices=[('pending', '待上传'), ('uploaded', '已上传'), ('verified', '已验证'), ('rejected', '已拒绝'), ('deleted', '已删除')], default='pending', max_length=16)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_asset',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', 'category', 'status'], name='media_asset_owner_i_b90c2c_idx')],
            },
        ),
    ]
