# Generated by Django 5.2.17 on 2026-09-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_alter_mediaasset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='category',
            field=models.CharField(choices=[('avatar', '用户头像'), ('provider_photo', '达人展示照片'), ('provider_video', '达人展示视频'), ('certification', '资质材料'), ('identity', '实名认证材料'), ('activity_cover', '活动封面'), ('review_image', '评价图片'), ('order_evidence', '履约证据'), ('support_attachment', '客服附件'), ('operations_icon', '运营图标'), ('operations_image', '运营图片'), ('other', '其他')], max_length=32),
        ),
    ]
