# Generated by Django 5.2.17 on 2026-08-15 16:42

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='标识')),
                ('icon_object_key', models.CharField(blank=True, max_length=512, verbose_name='图标对象键')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '活动分类',
                'verbose_name_plural': '活动分类',
                'db_table': 'activity_category',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('starts_at', models.DateTimeField(verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(verbose_name='结束时间')),
                ('formation_deadline', models.DateTimeField(verbose_name='成局截止时间')),
                ('meeting_place_name', models.CharField(max_length=100, verbose_name='集合地点名称')),
                ('meeting_address', models.CharField(max_length=255, verbose_name='集合地点地址')),
                ('map_source', models.CharField(choices=[('amap', '高德地图')], default='amap', max_length=16, verbose_name='地图来源')),
                ('source_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='原始GCJ-02经度')),
                ('source_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='原始GCJ-02纬度')),
                ('meeting_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='集合点（WGS84）')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='人数上限')),
                ('min_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='最少成局人数')),
                ('description', models.TextField(verbose_name='活动介绍')),
                ('participation_rules', models.TextField(verbose_name='参与规则')),
                ('aa_principal_amount', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='单人AA本金（分）')),
                ('refund_template_version', models.CharField(max_length=64, verbose_name='退款模板版本')),
                ('refund_rule_snapshot', models.JSONField(verbose_name='退款规则快照')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('recruiting', '报名中'), ('formed', '已成局'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('failed_to_form', '未成局')], default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='covered_activities', to='mediafiles.mediaasset', verbose_name='封面')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_activities', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitycategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity',
                'indexes': [models.Index(fields=['status', 'starts_at'], name='activity_status_467ad1_idx'), models.Index(fields=['category', 'status', 'starts_at'], name='activity_categor_1b3347_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='activity_end_after_start'), models.CheckConstraint(condition=models.Q(('formation_deadline__lt', models.F('starts_at'))), name='activity_deadline_before_start'), models.CheckConstraint(condition=models.Q(('min_participants__lte', models.F('capacity'))), name='activity_min_within_capacity')],
            },
        ),
    ]
