# Generated by Django 5.2.17 on 2026-08-20 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '已报名'), ('cancelled', '已取消')], default='active', max_length=16, verbose_name='状态')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_participations', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'db_table': 'activity_participation',
                'indexes': [models.Index(fields=['activity', 'status'], name='activity_pa_activit_77e985_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'user'), name='uniq_activity_participant')],
            },
        ),
    ]
