# Generated by Django 5.2.17 on 2026-08-20 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPublishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('aa_principal_amount', models.PositiveBigIntegerField(verbose_name='发起人AA本金（分）')),
                ('platform_service_fee_amount', models.PositiveBigIntegerField(verbose_name='平台服务费（分）')),
                ('payable_amount', models.PositiveBigIntegerField(verbose_name='应付金额（分）')),
                ('pricing_snapshot', models.JSONField(verbose_name='计价规则快照')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending_payment', max_length=20, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publish_order', to='activities.activity', verbose_name='活动')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_publish_orders', to=settings.AUTH_USER_MODEL, verbose_name='付款人')),
            ],
            options={
                'verbose_name': '活动发布支付单',
                'verbose_name_plural': '活动发布支付单',
                'db_table': 'activity_publish_order',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['payer', 'status', '-created_at'], name='activity_pu_payer_i_958d08_idx')],
            },
        ),
    ]
