# Generated by Django 5.2.17 on 2026-08-29 08:24

import activities.models
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipation',
            name='aa_principal_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='AA本金快照（分）'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='取消原因'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='cancelled_by_role',
            field=models.CharField(blank=True, choices=[('user', '参与者'), ('organizer', '发起人'), ('platform', '平台')], max_length=16, verbose_name='取消方'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='payable_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='应付金额快照（分）'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付失效时间'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='platform_service_fee_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='平台服务费快照（分）'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='计价规则快照'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='refund_rule_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='退款规则快照'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='rule_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款规则确认时间'),
        ),
        migrations.AddField(
            model_name='activityrefundrecord',
            name='retained_principal_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='扣除发起人AA本金（分）'),
        ),
        migrations.AddField(
            model_name='activityrefundrecord',
            name='retained_principal_destination',
            field=models.CharField(blank=True, max_length=16, verbose_name='扣除本金归属'),
        ),
        migrations.AddField(
            model_name='activityrefundrecord',
            name='retained_service_fee_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='扣除发起人平台服务费（分）'),
        ),
        migrations.AlterField(
            model_name='activityparticipation',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='activityparticipation',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待支付'), ('active', '已报名'), ('cancelled', '已取消'), ('expired', '支付超时')], default='pending_payment', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='activitypublishorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('partially_refunded', '部分退款'), ('refunded', '已退款')], default='pending_payment', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='activityrefundrecord',
            name='refund_type',
            field=models.CharField(choices=[('review_rejection', '审核驳回退款'), ('admin_cancellation', '后台取消退款'), ('organizer_cancellation', '发起人取消退款'), ('failed_to_form', '未成局退款')], max_length=24, verbose_name='退款类型'),
        ),
        migrations.CreateModel(
            name='ActivityParticipationPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default=activities.models.generate_participation_order_no, editable=False, max_length=24, unique=True, verbose_name='支付单号')),
                ('aa_principal_amount', models.PositiveBigIntegerField(verbose_name='AA本金（分）')),
                ('platform_service_fee_amount', models.PositiveBigIntegerField(verbose_name='平台服务费（分）')),
                ('payable_amount', models.PositiveBigIntegerField(verbose_name='应付金额（分）')),
                ('pricing_snapshot', models.JSONField(verbose_name='计价规则快照')),
                ('channel', models.CharField(choices=[('mock_wechat', '模拟微信支付'), ('mock_alipay', '模拟支付宝'), ('wechat', '微信支付'), ('alipay', '支付宝')], max_length=20, verbose_name='支付渠道')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('closed', '已关闭'), ('partially_refunded', '部分退款'), ('refunded', '已退款')], default='pending_payment', max_length=24, verbose_name='支付状态')),
                ('gateway_trade_no', models.CharField(blank=True, max_length=64, verbose_name='渠道交易号')),
                ('expires_at', models.DateTimeField(verbose_name='支付失效时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='activities.activityparticipation', verbose_name='活动报名')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_participation_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='付款人')),
            ],
            options={
                'verbose_name': '活动报名支付单',
                'verbose_name_plural': '活动报名支付单',
                'db_table': 'activity_participation_payment_order',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipationRefundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(default=activities.models.generate_participation_refund_no, editable=False, max_length=24, unique=True, verbose_name='退款单号')),
                ('idempotency_key', models.CharField(max_length=96, unique=True, verbose_name='幂等键')),
                ('refund_type', models.CharField(choices=[('participant_cancellation', '参与者取消'), ('organizer_cancellation', '发起人取消'), ('admin_cancellation', '后台取消'), ('failed_to_form', '未成局退款'), ('after_sales', '售后退款'), ('payment_timeout', '支付超时异常退款')], max_length=32, verbose_name='退款类型')),
                ('principal_refund_amount', models.PositiveBigIntegerField(verbose_name='AA本金退款（分）')),
                ('service_fee_refund_amount', models.PositiveBigIntegerField(verbose_name='平台服务费退款（分）')),
                ('refund_amount', models.PositiveBigIntegerField(verbose_name='退款总额（分）')),
                ('retained_principal_amount', models.PositiveBigIntegerField(default=0, verbose_name='扣除AA本金（分）')),
                ('retained_service_fee_amount', models.PositiveBigIntegerField(default=0, verbose_name='扣除平台服务费（分）')),
                ('retained_principal_destination', models.CharField(choices=[('none', '无扣除'), ('organizer', '归发起人'), ('platform', '归平台')], default='none', max_length=16, verbose_name='扣除本金归属')),
                ('status', models.CharField(choices=[('pending', '待退款'), ('processing', '退款处理中'), ('succeeded', '模拟退款成功'), ('failed', '退款失败')], default='pending', max_length=20, verbose_name='退款状态')),
                ('gateway_refund_no', models.CharField(blank=True, max_length=64, verbose_name='渠道退款号')),
                ('reason', models.CharField(max_length=1000, verbose_name='退款原因')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_refund_orders', to='activities.activity', verbose_name='活动')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_participation_refund_orders', to=settings.AUTH_USER_MODEL, verbose_name='退款用户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_activity_participation_refunds', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_orders', to='activities.activityparticipation', verbose_name='活动报名')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_orders', to='activities.activityparticipationpaymentorder', verbose_name='原支付单')),
            ],
            options={
                'verbose_name': '活动报名退款单',
                'verbose_name_plural': '活动报名退款单',
                'db_table': 'activity_participation_refund_order',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ActivityAfterSalesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(default=activities.models.generate_activity_after_sales_case_no, editable=False, max_length=24, unique=True, verbose_name='售后单号')),
                ('reason', models.CharField(choices=[('force_majeure', '不可抗力'), ('illness_or_accident', '疾病或事故'), ('false_information', '活动信息不实'), ('content_mismatch', '活动内容不符'), ('venue_change', '临时变更场地'), ('not_fulfilled', '活动未履约'), ('other', '其他问题')], max_length=32, verbose_name='售后原因')),
                ('description', models.CharField(max_length=1000, verbose_name='问题说明')),
                ('evidence_object_keys', models.JSONField(blank=True, default=list, verbose_name='证明材料对象键')),
                ('requested_principal_amount', models.PositiveBigIntegerField(verbose_name='申请AA本金退款（分）')),
                ('requested_service_fee_amount', models.PositiveBigIntegerField(verbose_name='申请平台服务费退款（分）')),
                ('requested_amount', models.PositiveBigIntegerField(verbose_name='申请退款总额（分）')),
                ('approved_principal_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='核准AA本金退款（分）')),
                ('approved_service_fee_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='核准平台服务费退款（分）')),
                ('approved_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='核准退款总额（分）')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('approved', '已同意'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('result_note', models.CharField(blank=True, max_length=1000, verbose_name='处理结论')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_after_sales_cases', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_cases', to='activities.activityparticipation', verbose_name='活动报名')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_activity_after_sales_cases', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('refund_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_case', to='activities.activityparticipationrefundorder', verbose_name='退款单')),
            ],
            options={
                'verbose_name': '活动退款售后单',
                'verbose_name_plural': '活动退款售后单',
                'db_table': 'activity_after_sales_case',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='activityparticipationpaymentorder',
            index=models.Index(fields=['payer', 'status', '-created_at'], name='activity_pa_payer_i_67dc93_idx'),
        ),
        migrations.AddIndex(
            model_name='activityparticipationpaymentorder',
            index=models.Index(fields=['expires_at', 'status'], name='activity_pa_expires_9a6487_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipationpaymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('payable_amount', django.db.models.expressions.CombinedExpression(models.F('aa_principal_amount'), '+', models.F('platform_service_fee_amount')))), name='activity_participation_payment_amount_matches'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipationpaymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending_payment')), fields=('participation',), name='uniq_pending_payment_per_activity_participation'),
        ),
        migrations.AddIndex(
            model_name='activityparticipationrefundorder',
            index=models.Index(fields=['activity', 'status', '-created_at'], name='activity_pa_activit_54c052_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipationrefundorder',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount', django.db.models.expressions.CombinedExpression(models.F('principal_refund_amount'), '+', models.F('service_fee_refund_amount')))), name='activity_participation_refund_amount_matches'),
        ),
        migrations.AddIndex(
            model_name='activityaftersalescase',
            index=models.Index(fields=['status', '-created_at'], name='activity_af_status_75a497_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityaftersalescase',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount', django.db.models.expressions.CombinedExpression(models.F('requested_principal_amount'), '+', models.F('requested_service_fee_amount')))), name='activity_after_sales_requested_amount_matches'),
        ),
        migrations.AddConstraint(
            model_name='activityaftersalescase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'processing'))), fields=('participation',), name='uniq_open_activity_after_sales_per_participation'),
        ),
    ]
