# Generated by Django 5.2.17 on 2026-08-29 15:50

import activities.models
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activityparticipation_aa_principal_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_no', models.CharField(default=activities.models.generate_activity_settlement_no, editable=False, max_length=24, unique=True, verbose_name='结算单号')),
                ('organizer_principal_amount', models.PositiveBigIntegerField(verbose_name='发起人AA本金（分）')),
                ('participant_principal_amount', models.PositiveBigIntegerField(verbose_name='有效参与者AA本金（分）')),
                ('retained_participant_principal_amount', models.PositiveBigIntegerField(verbose_name='取消参与者归发起人本金（分）')),
                ('settlement_amount', models.PositiveBigIntegerField(verbose_name='发起人结算金额（分）')),
                ('platform_service_fee_amount', models.PositiveBigIntegerField(verbose_name='平台组局服务费净额（分）')),
                ('status', models.CharField(choices=[('confirming', '履约确认中'), ('risk_frozen', '风险冻结中'), ('dispute_frozen', '争议冻结中'), ('settled', '已结算入账')], default='confirming', max_length=24, verbose_name='结算状态')),
                ('confirmation_started_at', models.DateTimeField(verbose_name='履约确认开始时间')),
                ('confirmation_deadline', models.DateTimeField(verbose_name='履约确认截止时间')),
                ('risk_frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='风险冻结开始时间')),
                ('freeze_until', models.DateTimeField(verbose_name='风险冻结截止时间')),
                ('dispute_reason', models.CharField(blank=True, max_length=1000, verbose_name='争议冻结原因')),
                ('dispute_source', models.CharField(blank=True, choices=[('', '无'), ('after_sales', '退款售后'), ('admin', '后台风控')], max_length=20, verbose_name='争议来源')),
                ('calculation_snapshot', models.JSONField(default=dict, verbose_name='结算计算快照')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算入账时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='activities.activity', verbose_name='活动')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_settlements', to=settings.AUTH_USER_MODEL, verbose_name='结算受益人')),
            ],
            options={
                'verbose_name': '活动结算单',
                'verbose_name_plural': '活动结算单',
                'db_table': 'activity_settlement',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'freeze_until'], name='activity_se_status_6466a2_idx'), models.Index(fields=['beneficiary', 'status', '-created_at'], name='activity_se_benefic_6c3f1a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('settlement_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('organizer_principal_amount'), '+', models.F('participant_principal_amount')), '+', models.F('retained_participant_principal_amount')))), name='activity_settlement_amount_matches_components'), models.CheckConstraint(condition=models.Q(('freeze_until__gte', models.F('confirmation_deadline'))), name='activity_settlement_freeze_after_confirmation')],
            },
        ),
    ]
