# Generated by Django 5.2.17 on 2026-09-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_publish_payment_expiry_and_refund_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrefundrecord',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=1000, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='activityrefundrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activityrefundrecord',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款时间'),
        ),
        migrations.AlterField(
            model_name='activityrefundrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待退款'), ('processing', '退款处理中'), ('succeeded', '退款成功'), ('failed', '退款失败'), ('simulated_refunded', '模拟退款成功')], default='simulated_refunded', max_length=24, verbose_name='退款状态'),
        ),
        migrations.CreateModel(
            name='ActivityHuifuPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preorder_status', models.CharField(choices=[('not_started', '未发起'), ('submitting', '预下单处理中'), ('ready', '预下单成功'), ('failed', '预下单失败')], default='not_started', max_length=16, verbose_name='汇付预下单状态')),
                ('gateway_merchant_id', models.CharField(blank=True, max_length=32, verbose_name='汇付商户号')),
                ('req_date', models.CharField(blank=True, max_length=8, verbose_name='汇付请求日期')),
                ('req_seq_id', models.CharField(blank=True, max_length=128, verbose_name='汇付请求流水号')),
                ('payment_scene', models.CharField(blank=True, max_length=32, verbose_name='支付场景')),
                ('trade_type', models.CharField(blank=True, max_length=16, verbose_name='汇付交易类型')),
                ('gateway_trade_no', models.CharField(blank=True, max_length=128, verbose_name='汇付全局流水号')),
                ('payment_invoke_payload', models.JSONField(blank=True, default=dict, verbose_name='客户端调起参数')),
                ('gateway_party_order_id', models.CharField(blank=True, max_length=64, verbose_name='渠道商户订单号')),
                ('gateway_out_trans_id', models.CharField(blank=True, max_length=64, verbose_name='渠道交易订单号')),
                ('gateway_response_code', models.CharField(blank=True, max_length=32, verbose_name='汇付响应码')),
                ('gateway_response_digest', models.CharField(blank=True, max_length=64, verbose_name='汇付响应摘要')),
                ('gateway_last_query_status', models.CharField(blank=True, max_length=8, verbose_name='最近查单状态')),
                ('gateway_last_query_digest', models.CharField(blank=True, max_length=64, verbose_name='最近查单响应摘要')),
                ('gateway_last_queried_at', models.DateTimeField(blank=True, null=True, verbose_name='最近查单时间')),
                ('preorder_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='预下单尝试次数')),
                ('preorder_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='预下单请求时间')),
                ('preorder_ready_at', models.DateTimeField(blank=True, null=True, verbose_name='预下单完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='huifu_payment', to='activities.activityparticipationpaymentorder', verbose_name='活动报名支付单')),
                ('publish_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='huifu_payment', to='activities.activitypublishorder', verbose_name='活动发布支付单')),
            ],
            options={
                'verbose_name': '活动汇付支付请求',
                'verbose_name_plural': '活动汇付支付请求',
                'db_table': 'activity_huifu_payment_order',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ActivityHuifuRefundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_merchant_id', models.CharField(blank=True, max_length=32, verbose_name='汇付商户号')),
                ('req_date', models.CharField(blank=True, max_length=8, verbose_name='汇付退款请求日期')),
                ('req_seq_id', models.CharField(blank=True, max_length=128, verbose_name='汇付退款请求流水号')),
                ('gateway_refund_no', models.CharField(blank=True, max_length=128, verbose_name='汇付退款全局流水号')),
                ('gateway_status', models.CharField(blank=True, max_length=8, verbose_name='渠道退款状态')),
                ('gateway_response_code', models.CharField(blank=True, max_length=32, verbose_name='汇付响应码')),
                ('gateway_response_digest', models.CharField(blank=True, max_length=64, verbose_name='汇付响应摘要')),
                ('gateway_last_query_status', models.CharField(blank=True, max_length=8, verbose_name='最近退款查询状态')),
                ('gateway_last_query_digest', models.CharField(blank=True, max_length=64, verbose_name='最近退款查询响应摘要')),
                ('gateway_last_queried_at', models.DateTimeField(blank=True, null=True, verbose_name='最近退款查询时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation_refund', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='huifu_refund', to='activities.activityparticipationrefundorder', verbose_name='活动报名退款单')),
                ('publish_refund', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='huifu_refund', to='activities.activityrefundrecord', verbose_name='活动发布退款单')),
            ],
            options={
                'verbose_name': '活动汇付退款请求',
                'verbose_name_plural': '活动汇付退款请求',
                'db_table': 'activity_huifu_refund_order',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ActivityHuifuNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64, unique=True, verbose_name='事件幂等键')),
                ('huifu_id', models.CharField(max_length=32, verbose_name='汇付商户号')),
                ('req_date', models.CharField(max_length=8, verbose_name='请求日期')),
                ('req_seq_id', models.CharField(max_length=128, verbose_name='请求流水号')),
                ('hf_seq_id', models.CharField(blank=True, max_length=128, verbose_name='汇付全局流水号')),
                ('trans_type', models.CharField(blank=True, max_length=32, verbose_name='交易类型')),
                ('notify_type', models.CharField(blank=True, max_length=8, verbose_name='通知类型')),
                ('trans_stat', models.CharField(blank=True, max_length=8, verbose_name='交易状态')),
                ('amount', models.CharField(blank=True, max_length=16, verbose_name='通知金额（元）')),
                ('payload_digest', models.CharField(max_length=64, verbose_name='通知报文摘要')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='验签通过')),
                ('query_response_digest', models.CharField(blank=True, max_length=64, verbose_name='主动查询响应摘要')),
                ('status', models.CharField(choices=[('received', '已接收'), ('processed', '已处理')], default='received', max_length=16, verbose_name='处理状态')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='activities.activityhuifupaymentorder')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='activities.activityhuifurefundorder')),
            ],
            options={
                'verbose_name': '活动汇付通知',
                'verbose_name_plural': '活动汇付通知',
                'db_table': 'activity_huifu_notification',
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='activityhuifupaymentorder',
            index=models.Index(fields=['preorder_status', '-updated_at'], name='activity_huifu_pay_pre_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityhuifupaymentorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participation_order__isnull', True), ('publish_order__isnull', False)), models.Q(('participation_order__isnull', False), ('publish_order__isnull', True)), _connector='OR'), name='activity_huifu_payment_one_business_order'),
        ),
        migrations.AddConstraint(
            model_name='activityhuifupaymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_trade_no', ''), _negated=True), fields=('gateway_trade_no',), name='uniq_activity_huifu_gateway_trade'),
        ),
        migrations.AddConstraint(
            model_name='activityhuifupaymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('req_seq_id', ''), _negated=True), fields=('req_date', 'req_seq_id'), name='uniq_activity_huifu_payment_request'),
        ),
        migrations.AddConstraint(
            model_name='activityhuifurefundorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participation_refund__isnull', True), ('publish_refund__isnull', False)), models.Q(('participation_refund__isnull', False), ('publish_refund__isnull', True)), _connector='OR'), name='activity_huifu_refund_one_business_order'),
        ),
        migrations.AddConstraint(
            model_name='activityhuifurefundorder',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_refund_no', ''), _negated=True), fields=('gateway_refund_no',), name='uniq_activity_huifu_gateway_refund'),
        ),
        migrations.AddConstraint(
            model_name='activityhuifurefundorder',
            constraint=models.UniqueConstraint(condition=models.Q(('req_seq_id', ''), _negated=True), fields=('req_date', 'req_seq_id'), name='uniq_activity_huifu_refund_request'),
        ),
        migrations.AddIndex(
            model_name='activityhuifunotification',
            index=models.Index(fields=['req_date', 'req_seq_id'], name='activity_huifu_notify_req_idx'),
        ),
        migrations.AddIndex(
            model_name='activityhuifunotification',
            index=models.Index(fields=['status', '-received_at'], name='act_huifu_notify_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityhuifunotification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment__isnull', False), ('refund__isnull', True)), models.Q(('payment__isnull', True), ('refund__isnull', False)), _connector='OR'), name='activity_huifu_notify_one_request'),
        ),
    ]
