# Generated by Django 5.2.17 on 2026-09-21 10:31

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_activity_tags(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    through = Activity.tags.through
    through.objects.bulk_create(
        [
            through(activity_id=activity_id, activitycategory_id=category_id)
            for activity_id, category_id in Activity.objects.exclude(
                category_id=None
            ).values_list("id", "category_id")
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_huifu_close_and_settlement_copy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitycategory",
            options={
                "ordering": ("sort_order", "id"),
                "verbose_name": "活动标签",
                "verbose_name_plural": "活动标签",
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='活动服务费率'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_activities', to='activities.activitycategory', verbose_name='活动标签'),
        ),
        migrations.RunPython(backfill_activity_tags, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitycategory', verbose_name='历史主标签'),
        ),
    ]
