# Generated by Django 5.2.17 on 2026-09-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_payment_wechat_payer_digest'),
        ('mediafiles', '0003_alter_mediaasset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='icon_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_category_icons', to='mediafiles.mediaasset', verbose_name='图标素材'),
        ),
    ]
