# Generated by Django 5.2.17 on 2026-08-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderWeeklyAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "一"),
                            (1, "二"),
                            (2, "三"),
                            (3, "四"),
                            (4, "五"),
                            (5, "六"),
                            (6, "日"),
                        ],
                        verbose_name="星期",
                    ),
                ),
                ("starts_at", models.TimeField(verbose_name="开始时间")),
                ("ends_at", models.TimeField(verbose_name="结束时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_availability",
                        to="providers.providerprofile",
                        verbose_name="达人",
                    ),
                ),
            ],
            options={
                "verbose_name": "达人每周可服务时段",
                "verbose_name_plural": "达人每周可服务时段",
                "db_table": "provider_weekly_availability",
                "ordering": ("weekday", "starts_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "weekday", "starts_at", "ends_at"),
                        name="uniq_provider_weekly_availability",
                    )
                ],
            },
        ),
    ]
