# Generated by Django 5.2.17 on 2026-08-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0003_alter_providerprofile_map_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="agreement_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="协议同意时间"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="invitation_code",
            field=models.CharField(blank=True, max_length=32, verbose_name="邀请码"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500, verbose_name="驳回原因"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="申请提交时间"),
        ),
    ]
