# Generated by Django 5.2.17 on 2026-08-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_providerprofile_agreement_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='is_accepting_orders',
            field=models.BooleanField(default=True, verbose_name='允许新预约'),
        ),
        migrations.CreateModel(
            name='ProviderDateAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('starts_at', models.TimeField(verbose_name='开始时间')),
                ('ends_at', models.TimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_availability', to='providers.providerprofile', verbose_name='达人')),
            ],
            options={
                'verbose_name': '达人临时可服务时段',
                'verbose_name_plural': '达人临时可服务时段',
                'db_table': 'provider_date_availability',
                'ordering': ('date', 'starts_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'date', 'starts_at', 'ends_at'), name='uniq_provider_date_availability')],
            },
        ),
        migrations.CreateModel(
            name='ProviderDateClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='休息日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_closures', to='providers.providerprofile', verbose_name='达人')),
            ],
            options={
                'verbose_name': '达人休息日',
                'verbose_name_plural': '达人休息日',
                'db_table': 'provider_date_closure',
                'constraints': [models.UniqueConstraint(fields=('provider', 'date'), name='uniq_provider_date_closure')],
            },
        ),
    ]
