# Generated by Django 5.2.17 on 2026-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_providerprofile_lifestyle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='admin_order_restricted',
            field=models.BooleanField(default=False, verbose_name='后台限制接单'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='admin_restriction_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='后台限制原因'),
        ),
    ]
