# Generated by Django 5.2.17 on 2026-09-04 23:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_provider_live_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='平台抽成比例（%）'),
        ),
    ]
