# Generated by Django 5.2.17 on 2026-09-10 14:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_provider_identity_status(apps, schema_editor):
    ProviderProfile = apps.get_model("providers", "ProviderProfile")
    ProviderProfile.objects.filter(user__verification_status="verified").update(
        identity_status="verified"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
        ('providers', '0012_servicecategory_platform_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='identity_back_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_identity_back_profiles', to='mediafiles.mediaasset', verbose_name='身份证国徽面'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_face_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_identity_face_profiles', to='mediafiles.mediaasset', verbose_name='本人核验照片'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_front_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_identity_front_profiles', to='mediafiles.mediaasset', verbose_name='身份证人像面'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_number_digest',
            field=models.CharField(blank=True, max_length=64, verbose_name='证件号码摘要'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_number_masked',
            field=models.CharField(blank=True, max_length=32, verbose_name='证件号码脱敏值'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='实名姓名'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_rejection_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='实名认证驳回原因'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实名认证审核时间'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_status',
            field=models.CharField(choices=[('unverified', '未认证'), ('pending', '认证中'), ('verified', '已认证'), ('rejected', '认证未通过')], default='unverified', max_length=16, verbose_name='达人实名认证状态'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实名认证提交时间'),
        ),
        migrations.RunPython(
            migrate_existing_provider_identity_status,
            migrations.RunPython.noop,
        ),
    ]
