# Generated by Django 5.2.17 on 2026-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_configure_initial_service_price_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='commission_reset_period_override',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='commission_tiers_override',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
