# Generated by Django 5.2.17 on 2026-09-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_alter_mediaasset_category'),
        ('providers', '0016_providerprofile_commission_reset_period_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediafiles.mediaasset')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='providers.providerprofile')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('provider', 'position'), name='uniq_provider_media_position'), models.UniqueConstraint(fields=('provider', 'asset'), name='uniq_provider_media_asset')],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfileRevisionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediafiles.mediaasset')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='providers.providerprofilerevision')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('revision', 'position'), name='uniq_revision_media_position'), models.UniqueConstraint(fields=('revision', 'asset'), name='uniq_revision_media_asset')],
            },
        ),
    ]
