# Generated by Django 5.2.17 on 2026-09-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_alter_mediaasset_category'),
        ('providers', '0018_backfill_profile_galleries'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_category_icons', to='mediafiles.mediaasset', verbose_name='图标素材'),
        ),
    ]
