# Generated by Django 5.2.17 on 2026-10-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0020_providerreceivingaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerreceivingaccount',
            options={'verbose_name': '达人收款账户', 'verbose_name_plural': '达人收款账户'},
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='audit_status',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='card_status',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='channel_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='channel_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='channel_scope',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='channel_status',
            field=models.CharField(default='not_connected', max_length=24),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='onboarding_consent_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='onboarding_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='settlement_status',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='providerreceivingaccount',
            name='user_huifu_id',
            field=models.CharField(blank=True, editable=False, max_length=18, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProviderReceivingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('req_seq_id', models.CharField(max_length=32, unique=True)),
                ('req_date', models.CharField(max_length=8)),
                ('status', models.CharField(default='sent', max_length=16)),
                ('settlement_config', models.JSONField(default=dict)),
                ('apply_no', models.CharField(blank=True, editable=False, max_length=18)),
                ('response_code', models.CharField(blank=True, max_length=8)),
                ('response_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='providers.providerreceivingaccount')),
            ],
            options={
                'db_table': 'provider_receiving_attempt',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ProviderReceivingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('notify_type', models.CharField(max_length=1)),
                ('audit_status', models.CharField(blank=True, max_length=1)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='providers.providerreceivingattempt')),
            ],
            options={
                'db_table': 'provider_receiving_notification',
            },
        ),
    ]
