# Generated by Django 5.2.17 on 2026-08-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('code', models.SlugField(unique=True, verbose_name='编码')),
                ('organization_type', models.CharField(choices=[('platform', '平台'), ('regional_agent', '区域代理'), ('city_agent', '城市代理')], max_length=20, verbose_name='类型')),
                ('city_codes', models.JSONField(blank=True, default=list, verbose_name='可管理城市编码')),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '停用')], default='active', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='backoffice.organization')),
            ],
            options={
                'verbose_name': '运营组织',
                'verbose_name_plural': '运营组织',
                'db_table': 'backoffice_organization',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.SlugField(verbose_name='角色编码')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限编码')),
                ('data_scope', models.CharField(choices=[('all', '全部数据'), ('organization', '本组织'), ('city', '指定城市')], max_length=20, verbose_name='数据范围')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='backoffice.organization')),
            ],
            options={
                'verbose_name': '后台角色',
                'verbose_name_plural': '后台角色',
                'db_table': 'backoffice_admin_role',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='操作')),
                ('target_type', models.CharField(max_length=80, verbose_name='对象类型')),
                ('target_id', models.CharField(max_length=80, verbose_name='对象ID')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='操作前')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='操作后')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='请求ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='backoffice.organization')),
            ],
            options={
                'verbose_name': '后台审计日志',
                'verbose_name_plural': '后台审计日志',
                'db_table': 'backoffice_admin_audit_log',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_codes', models.JSONField(blank=True, default=list, verbose_name='额外城市范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='backoffice.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='backoffice.adminrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backoffice_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '后台成员',
                'verbose_name_plural': '后台成员',
                'db_table': 'backoffice_organization_member',
            },
        ),
        migrations.AddConstraint(
            model_name='adminrole',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_backoffice_role_org_code'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='backoffice__target__9d2b14_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uniq_backoffice_member_user_org'),
        ),
    ]
