# Generated by Django 5.2.17 on 2026-08-23 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
        ('orders', '0004_providerorder_fulfillment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrderSupportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='客服备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_order_support_notes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_notes', to='orders.providerorder')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_order_support_notes', to='backoffice.organization')),
            ],
            options={
                'verbose_name': '订单客服备注',
                'verbose_name_plural': '订单客服备注',
                'db_table': 'backoffice_provider_order_support_note',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['order', 'created_at'], name='backoffice__order_i_dcb663_idx')],
            },
        ),
    ]
