# Generated by Django 5.2.17 on 2026-08-23 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_grant_fulfillment_permissions'),
        ('providers', '0008_providerprofile_admin_order_restricted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', '一般关注'), ('medium', '重点关注'), ('high', '高风险')], default='medium', max_length=16, verbose_name='风险等级')),
                ('reason', models.CharField(max_length=500, verbose_name='标记原因')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前生效')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='标记时间')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_user_risk_flags', to=settings.AUTH_USER_MODEL, verbose_name='解除人')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_user_risk_flags', to=settings.AUTH_USER_MODEL, verbose_name='标记人')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_risk_flags', to='backoffice.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admin_risk_flag', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户风险标记',
                'verbose_name_plural': '用户风险标记',
                'db_table': 'backoffice_user_risk_flag',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProviderCreditAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='调整分值')),
                ('before_score', models.PositiveSmallIntegerField(verbose_name='调整前分值')),
                ('after_score', models.PositiveSmallIntegerField(verbose_name='调整后分值')),
                ('reason', models.CharField(max_length=500, verbose_name='调整原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_credit_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_credit_adjustments', to='backoffice.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_credit_adjustments', to='providers.providerprofile', verbose_name='达人')),
            ],
            options={
                'verbose_name': '达人信用分调整',
                'verbose_name_plural': '达人信用分调整',
                'db_table': 'backoffice_provider_credit_adjustment',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['provider', '-created_at'], name='backoffice__provide_9bef26_idx')],
            },
        ),
    ]
