# Generated by Django 5.2.17 on 2026-08-23 07:25

import backoffice.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_grant_user_provider_management_permissions'),
        ('orders', '0004_providerorder_fulfillment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrderAfterSalesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_no', models.CharField(default=backoffice.models.generate_after_sales_case_no, editable=False, max_length=24, unique=True, verbose_name='售后单号')),
                ('case_type', models.CharField(choices=[('refund', '退款申请'), ('service_dispute', '服务争议'), ('provider_cancel', '达人取消'), ('other', '其他售后')], max_length=24, verbose_name='售后类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('approved', '已同意·待退款'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('original_order_status', models.CharField(max_length=24, verbose_name='订单原状态')),
                ('requested_amount', models.PositiveBigIntegerField(default=0, verbose_name='申请退款金额（分）')),
                ('approved_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='核准退款金额（分）')),
                ('reason', models.CharField(max_length=1000, verbose_name='申请原因')),
                ('result_note', models.CharField(blank=True, max_length=1000, verbose_name='审核结论')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_provider_order_after_sales_cases', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_cases', to='orders.providerorder')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_order_after_sales_cases', to='backoffice.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_provider_order_after_sales_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单退款售后单',
                'verbose_name_plural': '订单退款售后单',
                'db_table': 'backoffice_provider_order_after_sales_case',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='backoffice__status_c1501e_idx'), models.Index(fields=['case_type', '-created_at'], name='backoffice__case_ty_861e13_idx'), models.Index(fields=['organization', 'status', '-created_at'], name='backoffice__organiz_fe18b5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('approved_amount__isnull', True), ('approved_amount__lte', models.F('requested_amount')), _connector='OR'), name='after_sales_approved_lte_requested'), models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'processing', 'approved'))), fields=('order',), name='uniq_open_after_sales_case_per_order')],
            },
        ),
    ]
