# Generated by Django 5.2.17 on 2026-08-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_grant_activity_settlement_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrderingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, unique=True)),
                ('location_report_interval_seconds', models.PositiveSmallIntegerField(default=300)),
                ('location_timeout_minutes', models.PositiveSmallIntegerField(default=30)),
                ('max_location_accuracy_m', models.PositiveSmallIntegerField(default=200)),
                ('acceptance_timeout_minutes', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '达人接单规则',
                'verbose_name_plural': '达人接单规则',
                'db_table': 'backoffice_provider_ordering_setting',
            },
        ),
    ]
