# Generated by Django 5.2.17 on 2026-08-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0014_grant_operations_manage_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformOperationSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.CharField(default="default", editable=False, max_length=20, unique=True)),
                ("provider_order_payment_timeout_minutes", models.PositiveSmallIntegerField(default=15)),
                ("provider_order_confirmation_timeout_days", models.PositiveSmallIntegerField(default=3)),
                ("activity_payment_timeout_minutes", models.PositiveSmallIntegerField(default=30)),
                ("activity_minimum_advance_hours", models.PositiveSmallIntegerField(default=48)),
                ("activity_maximum_advance_days", models.PositiveSmallIntegerField(default=30)),
                ("activity_settlement_confirmation_hours", models.PositiveSmallIntegerField(default=24)),
                ("activity_settlement_risk_freeze_days", models.PositiveSmallIntegerField(default=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "平台运营参数",
                "verbose_name_plural": "平台运营参数",
                "db_table": "backoffice_platform_operation_setting",
            },
        ),
    ]
