# Generated by Django 5.2.17 on 2026-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_grant_support_case_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_order_settlement_freeze_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='providerorderaftersalescase',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('approved', '已同意·待退款'), ('refunded', '退款成功'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
    ]
