# Generated by Django 5.2.17 on 2026-09-21 10:31

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_providerorderaftersalescase_evidence_object_keys'),
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationsetting',
            name='activity_max_aa_principal_amount',
            field=models.PositiveBigIntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='activity_max_capacity',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='activity_min_aa_principal_amount',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='activity_min_capacity',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='activity_service_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='default_activity_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_default_activity_cover_settings', to='mediafiles.mediaasset'),
        ),
    ]
