# Generated by Django 5.2.17 on 2026-09-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_platformoperationsetting_activity_max_aa_principal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationsetting',
            name='customer_service_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
