# Generated by Django 5.2.17 on 2026-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_platformoperationsetting_customer_service_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_commission_reset_period',
            field=models.CharField(default='month', max_length=16),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_commission_tiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_order_review_timeout_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='report_coupon_amount',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='report_coupon_min_order_amount',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='report_coupon_valid_days',
            field=models.PositiveSmallIntegerField(default=365),
        ),
    ]
