# Generated by Django 5.2.17 on 2026-10-07 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0032_fulfillment_tolerances'),
        ('orders', '0033_coupon_issue_batches'),
        ('providers', '0023_first_order_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_order_departure_grace_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_order_no_departure_credit_penalty',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='providercreditadjustment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_adjustments', to='orders.providerorder'),
        ),
        migrations.AddField(
            model_name='providercreditadjustment',
            name='source',
            field=models.CharField(choices=[('manual', '人工调整'), ('no_departure', '未出发超时'), ('no_departure_reversal', '未出发超时申诉撤销')], default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='providercreditadjustment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_credit_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddConstraint(
            model_name='providercreditadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'manual'), _negated=True), fields=('order', 'source'), name='credit_order_system_event_unique'),
        ),
    ]
