# Generated by Django 5.2.17 on 2026-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0036_early_termination_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_cancellation_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='取消规则参数'),
        ),
        migrations.AddField(
            model_name='platformoperationsetting',
            name='provider_cancellation_enabled',
            field=models.BooleanField(default=False, verbose_name='新订单取消规则开关'),
        ),
    ]
