# Generated by Django 5.2.17 on 2026-09-03 13:09

import django.db.models.deletion
import supportcases.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0008_activitysettlement"),
        ("mediafiles", "0001_initial"),
        ("orders", "0010_providerorderreview_images_and_more"),
        ("providers", "0011_provider_live_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "case_no",
                    models.CharField(
                        default=supportcases.models.generate_support_case_no,
                        editable=False,
                        max_length=24,
                        unique=True,
                        verbose_name="工单号",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("consultation", "咨询"),
                            ("complaint", "投诉"),
                            ("report", "举报"),
                        ],
                        max_length=20,
                        verbose_name="工单类型",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("general", "平台服务"),
                            ("provider", "达人"),
                            ("provider_order", "达人订单"),
                            ("activity", "活动"),
                            ("review", "用户评价"),
                        ],
                        max_length=24,
                        verbose_name="关联对象",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("service_quality", "服务体验问题"),
                            ("false_information", "信息不实"),
                            ("inappropriate_content", "内容不当"),
                            ("private_transaction", "诱导私下交易"),
                            ("safety_risk", "存在安全风险"),
                            ("payment_refund", "支付或退款问题"),
                            ("account_issue", "账号问题"),
                            ("other", "其他问题"),
                        ],
                        max_length=32,
                        verbose_name="问题分类",
                    ),
                ),
                ("description", models.CharField(max_length=1000, verbose_name="问题说明")),
                ("city_code", models.CharField(blank=True, max_length=20, verbose_name="城市编码快照")),
                ("city_name", models.CharField(blank=True, max_length=50, verbose_name="城市名称快照")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待受理"),
                            ("processing", "处理中"),
                            ("reviewing", "复核中"),
                            ("resolved", "已处理"),
                            ("rejected", "不予受理"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("result_note", models.CharField(blank=True, max_length=1000, verbose_name="处理结论")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="完结时间")),
                ("review_requested_at", models.DateTimeField(blank=True, null=True, verbose_name="申请复核时间")),
                ("review_reason", models.CharField(blank=True, max_length=1000, verbose_name="复核原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_cases",
                        to="activities.activity",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_support_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="support_cases",
                        to="mediafiles.mediaasset",
                        verbose_name="证据附件",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_cases",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "provider_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_cases",
                        to="orders.providerorder",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_cases",
                        to="orders.providerorderreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "客服工单",
                "verbose_name_plural": "客服工单",
                "db_table": "support_case",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SupportCaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("created", "提交工单"),
                            ("user_reply", "用户补充"),
                            ("operator_reply", "客服回复"),
                            ("status_changed", "状态变更"),
                            ("review_requested", "申请复核"),
                        ],
                        max_length=24,
                        verbose_name="记录类型",
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=1000, verbose_name="记录内容")),
                ("from_status", models.CharField(blank=True, max_length=20, verbose_name="原状态")),
                ("to_status", models.CharField(blank=True, max_length=20, verbose_name="新状态")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_case_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="supportcases.supportcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "工单处理记录",
                "verbose_name_plural": "工单处理记录",
                "db_table": "support_case_record",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(fields=["status", "-created_at"], name="support_cas_status_9104ea_idx"),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(fields=["city_code", "status", "-created_at"], name="support_cas_city_co_4e1e54_idx"),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(fields=["reporter", "-created_at"], name="support_cas_reporte_8b7002_idx"),
        ),
        migrations.AddConstraint(
            model_name="supportcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activity__isnull", True),
                        ("provider__isnull", True),
                        ("provider_order__isnull", True),
                        ("review__isnull", True),
                        ("target_type", "general"),
                    ),
                    models.Q(
                        ("activity__isnull", True),
                        ("provider__isnull", False),
                        ("provider_order__isnull", True),
                        ("review__isnull", True),
                        ("target_type", "provider"),
                    ),
                    models.Q(
                        ("activity__isnull", True),
                        ("provider__isnull", True),
                        ("provider_order__isnull", False),
                        ("review__isnull", True),
                        ("target_type", "provider_order"),
                    ),
                    models.Q(
                        ("activity__isnull", False),
                        ("provider__isnull", True),
                        ("provider_order__isnull", True),
                        ("review__isnull", True),
                        ("target_type", "activity"),
                    ),
                    models.Q(
                        ("activity__isnull", True),
                        ("provider__isnull", True),
                        ("provider_order__isnull", True),
                        ("review__isnull", False),
                        ("target_type", "review"),
                    ),
                    _connector="OR",
                ),
                name="support_case_target_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("provider__isnull", False),
                    ("status__in", ("pending", "processing", "reviewing")),
                ),
                fields=("reporter", "provider"),
                name="uniq_open_support_case_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("provider_order__isnull", False),
                    ("status__in", ("pending", "processing", "reviewing")),
                ),
                fields=("reporter", "provider_order"),
                name="uniq_open_support_case_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("activity__isnull", False),
                    ("status__in", ("pending", "processing", "reviewing")),
                ),
                fields=("reporter", "activity"),
                name="uniq_open_support_case_activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("review__isnull", False),
                    ("status__in", ("pending", "processing", "reviewing")),
                ),
                fields=("reporter", "review"),
                name="uniq_open_support_case_review",
            ),
        ),
        migrations.AddIndex(
            model_name="supportcaserecord",
            index=models.Index(fields=["case", "created_at"], name="support_cas_case_id_e929cf_idx"),
        ),
    ]
