# Generated by Django 5.2.17 on 2026-09-23 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_activity_service_fee_rate_activity_tags_and_more'),
        ('mediafiles', '0001_initial'),
        ('orders', '0020_providerorder_review_expires_at_and_more'),
        ('providers', '0016_providerprofile_commission_reset_period_override_and_more'),
        ('supportcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supportcase',
            name='uniq_open_support_case_order',
        ),
        migrations.AddField(
            model_name='supportcase',
            name='reward_coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_support_case', to='orders.usercoupon'),
        ),
        migrations.AddField(
            model_name='supportcase',
            name='reward_eligible',
            field=models.BooleanField(default=False, verbose_name='举报有奖'),
        ),
        migrations.AddConstraint(
            model_name='supportcase',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_order__isnull', False), ('status__in', ('pending', 'processing', 'reviewing'))), fields=('reporter', 'provider_order', 'case_type'), name='uniq_open_support_case_order'),
        ),
        migrations.AddConstraint(
            model_name='supportcase',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_order__isnull', False), ('reward_eligible', True)), fields=('reporter', 'provider_order'), name='uniq_reward_report_per_order'),
        ),
    ]
