# Generated by Django 5.2.17 on 2026-09-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportcases', '0002_remove_supportcase_uniq_open_support_case_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcase',
            name='reason',
            field=models.CharField(choices=[('platform_process', '平台流程问题'), ('platform_product', '产品体验建议'), ('service_quality', '服务体验问题'), ('false_information', '信息不实'), ('inappropriate_content', '内容不当'), ('private_transaction', '诱导私下交易'), ('safety_risk', '存在安全风险'), ('payment_refund', '支付或退款问题'), ('account_issue', '账号问题'), ('other', '其他问题')], max_length=32, verbose_name='问题分类'),
        ),
    ]
