# Generated by Django 5.2.6 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supportcases", "0003_alter_supportcase_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportcase",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("consultation", "咨询"),
                    ("complaint", "投诉/反馈"),
                    ("report", "举报"),
                ],
                max_length=20,
                verbose_name="工单类型",
            ),
        ),
    ]
