# Generated by Django 5.2.17 on 2026-08-15 15:49

import accounts.managers
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('unspecified', '未设置'), ('male', '男'), ('female', '女')], default='unspecified', max_length=16, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('avatar_object_key', models.CharField(blank=True, max_length=512, verbose_name='头像对象键')),
                ('verification_status', models.CharField(choices=[('unverified', '未认证'), ('pending', '认证中'), ('verified', '已认证'), ('rejected', '认证未通过')], default='unverified', max_length=16, verbose_name='实名认证状态')),
                ('account_status', models.CharField(choices=[('active', '正常'), ('restricted', '受限'), ('suspended', '停用'), ('closed', '已注销')], default='active', max_length=16, verbose_name='账号状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
