# Generated by Django 5.2.6 on 2026-09-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_wechatofficialaccountidentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="WechatMiniProgramIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=32, verbose_name="小程序 AppID")),
                ("openid", models.CharField(max_length=128, verbose_name="小程序 OpenID")),
                (
                    "unionid",
                    models.CharField(blank=True, max_length=128, verbose_name="微信 UnionID"),
                ),
                ("authorized_at", models.DateTimeField(verbose_name="最近授权时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wechat_mini_program_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "微信小程序身份",
                "verbose_name_plural": "微信小程序身份",
                "db_table": "accounts_wechat_mini_program_identity",
            },
        ),
        migrations.AddConstraint(
            model_name="wechatminiprogramidentity",
            constraint=models.UniqueConstraint(
                fields=("user", "app_id"), name="uniq_wechat_mini_user_app"
            ),
        ),
        migrations.AddConstraint(
            model_name="wechatminiprogramidentity",
            constraint=models.UniqueConstraint(
                fields=("app_id", "openid"), name="uniq_wechat_mini_app_openid"
            ),
        ),
    ]
