# Generated by Django 5.2.17 on 2026-09-29 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wechatunionidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', '正常'), ('restricted', '受限'), ('suspended', '停用'), ('closure_pending', '注销申请处理中'), ('closed', '已注销')], default='active', max_length=16, verbose_name='账号状态'),
        ),
        migrations.CreateModel(
            name='AccountClosureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('execute_after', models.DateTimeField(verbose_name='最早注销时间')),
                ('status', models.CharField(choices=[('pending', '等待注销'), ('blocked', '未结业务暂停处理'), ('cancelled', '登录撤销'), ('completed', '已完成注销')], default='pending', max_length=16)),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成或撤销时间')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('blocking_items', models.JSONField(blank=True, default=list, verbose_name='待处理业务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '账号注销申请',
                'verbose_name_plural': '账号注销申请',
                'db_table': 'accounts_closure_request',
                'indexes': [models.Index(fields=['status', 'execute_after'], name='accounts_cl_status_7ef98c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'blocked'))), fields=('user',), name='uniq_open_account_closure')],
            },
        ),
    ]
