# Generated manually for the wallet and recharge ledger.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

import wallets.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("accounts", "0004_wechatminiprogramidentity")]

    operations = [
        migrations.CreateModel(
            name="RechargeCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="开放充值")),
                ("unit_face_amount", models.PositiveBigIntegerField(default=100000, verbose_name="单张面值（分）")),
                ("max_quantity_per_order", models.PositiveSmallIntegerField(default=10, verbose_name="单次最多购买张数")),
                ("rules_text", models.CharField(default="充值余额仅限平台消费，不可提现；退款按订单原支付构成退回。", max_length=500, verbose_name="充值说明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="updated_recharge_campaigns", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "充值活动配置", "verbose_name_plural": "充值活动配置", "db_table": "wallet_recharge_campaign"},
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("available_balance", models.PositiveBigIntegerField(default=0, verbose_name="可用余额（分）")),
                ("frozen_balance", models.PositiveBigIntegerField(default=0, verbose_name="冻结余额（分）")),
                ("version", models.PositiveBigIntegerField(default=0, editable=False, verbose_name="账本版本")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="wallet", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
            ],
            options={"verbose_name": "用户钱包", "verbose_name_plural": "用户钱包", "db_table": "user_wallet"},
        ),
        migrations.CreateModel(
            name="WalletRechargeOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_no", models.CharField(default=wallets.models.generate_recharge_order_no, editable=False, max_length=24, unique=True, verbose_name="充值单号")),
                ("unit_face_amount", models.PositiveBigIntegerField(verbose_name="单张面值（分）")),
                ("quantity", models.PositiveSmallIntegerField(verbose_name="购买张数")),
                ("credited_amount", models.PositiveBigIntegerField(verbose_name="入账金额（分）")),
                ("discount_rate_bps", models.PositiveSmallIntegerField(verbose_name="折扣比例（万分比）")),
                ("discount_amount", models.PositiveBigIntegerField(verbose_name="优惠金额（分）")),
                ("payable_amount", models.PositiveBigIntegerField(verbose_name="实付金额（分）")),
                ("pricing_snapshot", models.JSONField(default=dict, verbose_name="充值计价快照")),
                ("status", models.CharField(choices=[("pending_payment", "待支付"), ("paid", "已入账"), ("closed", "已关闭")], default="pending_payment", max_length=24, verbose_name="状态")),
                ("preorder_status", models.CharField(choices=[("not_started", "未发起"), ("submitting", "预下单处理中"), ("ready", "预下单成功"), ("failed", "预下单失败")], default="not_started", max_length=16, verbose_name="汇付预下单状态")),
                ("gateway_merchant_id", models.CharField(blank=True, max_length=32, verbose_name="汇付商户号")),
                ("req_date", models.CharField(blank=True, max_length=8, verbose_name="汇付请求日期")),
                ("req_seq_id", models.CharField(blank=True, max_length=128, verbose_name="汇付请求流水号")),
                ("payment_scene", models.CharField(blank=True, max_length=32, verbose_name="支付场景")),
                ("trade_type", models.CharField(blank=True, max_length=16, verbose_name="汇付交易类型")),
                ("gateway_trade_no", models.CharField(blank=True, max_length=128, verbose_name="汇付全局流水号")),
                ("gateway_party_order_id", models.CharField(blank=True, max_length=64, verbose_name="渠道商户订单号")),
                ("gateway_out_trans_id", models.CharField(blank=True, max_length=64, verbose_name="渠道交易订单号")),
                ("payment_invoke_payload", models.JSONField(blank=True, default=dict, verbose_name="客户端调起参数")),
                ("gateway_response_code", models.CharField(blank=True, max_length=32, verbose_name="汇付响应码")),
                ("gateway_response_digest", models.CharField(blank=True, max_length=64, verbose_name="汇付响应摘要")),
                ("gateway_last_query_status", models.CharField(blank=True, max_length=8, verbose_name="最近查单状态")),
                ("gateway_last_query_digest", models.CharField(blank=True, max_length=64, verbose_name="最近查单摘要")),
                ("gateway_last_queried_at", models.DateTimeField(blank=True, null=True, verbose_name="最近查单时间")),
                ("preorder_attempts", models.PositiveSmallIntegerField(default=0, verbose_name="预下单尝试次数")),
                ("preorder_requested_at", models.DateTimeField(blank=True, null=True, verbose_name="预下单请求时间")),
                ("preorder_ready_at", models.DateTimeField(blank=True, null=True, verbose_name="预下单完成时间")),
                ("expires_at", models.DateTimeField(verbose_name="支付失效时间")),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="支付时间")),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="关闭时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wallet_recharge_orders", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
            ],
            options={"verbose_name": "钱包充值订单", "verbose_name_plural": "钱包充值订单", "db_table": "wallet_recharge_order", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="WalletPaymentAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_type", models.CharField(choices=[("provider_order", "达人订单"), ("activity_publish", "活动发布"), ("activity_participation", "活动报名")], max_length=32)),
                ("business_order_no", models.CharField(max_length=64)),
                ("payable_amount", models.PositiveBigIntegerField(verbose_name="订单应付（分）")),
                ("wallet_amount", models.PositiveBigIntegerField(default=0, verbose_name="余额支付（分）")),
                ("external_amount", models.PositiveBigIntegerField(default=0, verbose_name="外部支付（分）")),
                ("wallet_refunded_amount", models.PositiveBigIntegerField(default=0, verbose_name="余额已退（分）")),
                ("external_refunded_amount", models.PositiveBigIntegerField(default=0, verbose_name="外部已退（分）")),
                ("status", models.CharField(choices=[("held", "余额已冻结"), ("consumed", "余额已扣款"), ("released", "余额已解冻"), ("partially_refunded", "部分退款"), ("refunded", "已退款")], default="held", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wallet_payment_allocations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "钱包支付分配", "verbose_name_plural": "钱包支付分配", "db_table": "wallet_payment_allocation"},
        ),
        migrations.CreateModel(
            name="WalletLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("entry_type", models.CharField(choices=[("recharge", "充值入账"), ("payment_hold", "支付冻结"), ("payment_consume", "支付扣款"), ("payment_release", "支付解冻"), ("refund", "退款入账"), ("admin_adjustment", "后台调账")], max_length=24, verbose_name="流水类型")),
                ("available_delta", models.BigIntegerField(default=0, verbose_name="可用余额变动（分）")),
                ("frozen_delta", models.BigIntegerField(default=0, verbose_name="冻结余额变动（分）")),
                ("available_balance_after", models.PositiveBigIntegerField(verbose_name="变动后可用余额（分）")),
                ("frozen_balance_after", models.PositiveBigIntegerField(verbose_name="变动后冻结余额（分）")),
                ("idempotency_key", models.CharField(max_length=160, unique=True, verbose_name="幂等键")),
                ("reference_type", models.CharField(max_length=40, verbose_name="关联类型")),
                ("reference_no", models.CharField(max_length=64, verbose_name="关联单号")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="说明")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="扩展信息")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="wallets.userwallet", verbose_name="钱包")),
            ],
            options={"verbose_name": "钱包流水", "verbose_name_plural": "钱包流水", "db_table": "wallet_ledger_entry", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="RechargeDiscountTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_quantity", models.PositiveSmallIntegerField(verbose_name="起始张数")),
                ("discount_rate_bps", models.PositiveSmallIntegerField(default=10000, verbose_name="折扣比例（万分比）")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="discount_tiers", to="wallets.rechargecampaign", verbose_name="充值活动")),
            ],
            options={"verbose_name": "充值折扣档位", "verbose_name_plural": "充值折扣档位", "db_table": "wallet_recharge_discount_tier", "ordering": ("min_quantity", "id")},
        ),
        migrations.CreateModel(
            name="WalletRechargeNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_key", models.CharField(max_length=64, unique=True, verbose_name="事件幂等键")),
                ("payload_digest", models.CharField(max_length=64, verbose_name="报文摘要")),
                ("trans_stat", models.CharField(blank=True, max_length=8, verbose_name="交易状态")),
                ("hf_seq_id", models.CharField(blank=True, max_length=128, verbose_name="汇付全局流水号")),
                ("signature_verified", models.BooleanField(default=False)),
                ("query_response_digest", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("received", "已接收"), ("processed", "已处理")], default="received", max_length=16)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("recharge_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="huifu_notifications", to="wallets.walletrechargeorder")),
            ],
            options={"db_table": "wallet_recharge_notification", "ordering": ("-received_at", "-id")},
        ),
        migrations.AddIndex(model_name="walletrechargeorder", index=models.Index(fields=["user", "status", "-created_at"], name="wallet_recharge_user_idx")),
        migrations.AddIndex(model_name="walletrechargeorder", index=models.Index(fields=["status", "expires_at"], name="wallet_recharge_exp_idx")),
        migrations.AddIndex(model_name="walletledgerentry", index=models.Index(fields=["wallet", "-created_at"], name="wallet_ledger_owner_idx")),
        migrations.AddIndex(model_name="walletledgerentry", index=models.Index(fields=["reference_type", "reference_no"], name="wallet_ledger_ref_idx")),
        migrations.AddConstraint(model_name="rechargecampaign", constraint=models.CheckConstraint(condition=models.Q(("singleton_key", 1)), name="wallet_recharge_singleton_key")),
        migrations.AddConstraint(model_name="rechargecampaign", constraint=models.CheckConstraint(condition=models.Q(("unit_face_amount__gt", 0)), name="wallet_recharge_unit_positive")),
        migrations.AddConstraint(model_name="rechargecampaign", constraint=models.CheckConstraint(condition=models.Q(("max_quantity_per_order__gte", 1), ("max_quantity_per_order__lte", 99)), name="wallet_recharge_quantity_valid")),
        migrations.AddConstraint(model_name="rechargediscounttier", constraint=models.UniqueConstraint(fields=("campaign", "min_quantity"), name="uniq_recharge_campaign_quantity")),
        migrations.AddConstraint(model_name="rechargediscounttier", constraint=models.CheckConstraint(condition=models.Q(("min_quantity__gte", 1), ("min_quantity__lte", 99)), name="recharge_tier_quantity_valid")),
        migrations.AddConstraint(model_name="rechargediscounttier", constraint=models.CheckConstraint(condition=models.Q(("discount_rate_bps__gte", 1), ("discount_rate_bps__lte", 10000)), name="recharge_tier_discount_valid")),
        migrations.AddConstraint(model_name="walletrechargeorder", constraint=models.CheckConstraint(condition=models.Q(("credited_amount", models.F("unit_face_amount") * models.F("quantity"))), name="wallet_recharge_credit_matches")),
        migrations.AddConstraint(model_name="walletrechargeorder", constraint=models.CheckConstraint(condition=models.Q(("payable_amount", models.F("credited_amount") - models.F("discount_amount"))), name="wallet_recharge_payable_matches")),
        migrations.AddConstraint(model_name="walletrechargeorder", constraint=models.UniqueConstraint(condition=models.Q(("req_seq_id", ""), _negated=True), fields=("req_date", "req_seq_id"), name="uniq_wallet_recharge_huifu_request")),
        migrations.AddConstraint(model_name="walletrechargeorder", constraint=models.UniqueConstraint(condition=models.Q(("gateway_trade_no", ""), _negated=True), fields=("gateway_trade_no",), name="uniq_wallet_recharge_gateway_trade")),
        migrations.AddConstraint(model_name="walletledgerentry", constraint=models.CheckConstraint(condition=models.Q(("available_delta", 0), ("frozen_delta", 0), _negated=True), name="wallet_ledger_nonzero_delta")),
        migrations.AddConstraint(model_name="walletpaymentallocation", constraint=models.UniqueConstraint(fields=("business_type", "business_order_no"), name="uniq_wallet_business_allocation")),
        migrations.AddConstraint(model_name="walletpaymentallocation", constraint=models.CheckConstraint(condition=models.Q(("payable_amount", models.F("wallet_amount") + models.F("external_amount"))), name="wallet_allocation_amount_matches")),
        migrations.AddConstraint(model_name="walletpaymentallocation", constraint=models.CheckConstraint(condition=models.Q(("wallet_refunded_amount__lte", models.F("wallet_amount"))), name="wallet_refund_lte_wallet_paid")),
        migrations.AddConstraint(model_name="walletpaymentallocation", constraint=models.CheckConstraint(condition=models.Q(("external_refunded_amount__lte", models.F("external_amount"))), name="external_refund_lte_external_paid")),
    ]
