# Generated by Django 5.2.17 on 2026-09-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRefundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=64, unique=True)),
                ('wallet_amount', models.PositiveBigIntegerField(default=0)),
                ('external_amount', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.walletpaymentallocation')),
            ],
            options={
                'db_table': 'wallet_refund_receipt',
            },
        ),
    ]
