# Generated by Django 5.2.17 on 2026-09-25 16:42

from django.db import migrations, models


def backfill_released(apps, schema_editor):
    allocation = apps.get_model("wallets", "WalletPaymentAllocation")
    ledger = apps.get_model("wallets", "WalletLedgerEntry")
    release_entries = ledger.objects.filter(
        entry_type="payment_release",
        reference_type=models.OuterRef("business_type"),
        reference_no=models.OuterRef("business_order_no"),
    )
    allocation.objects.annotate(had_release=models.Exists(release_entries)).filter(
        models.Q(status="released") | models.Q(had_release=True)
    ).update(wallet_released=True)


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_walletrefundreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpaymentallocation',
            name='wallet_released',
            field=models.BooleanField(default=False, verbose_name='余额已解冻且未扣款'),
        ),
        migrations.RunPython(backfill_released, migrations.RunPython.noop),
    ]
