# Generated by Django 5.2.17 on 2026-09-01 00:39

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_type', models.CharField(choices=[('provider_order_payment_expiry', '达人订单支付超时'), ('provider_acceptance_timeout', '达人接单超时')], max_length=64, verbose_name='任务类型')),
                ('business_type', models.CharField(max_length=40, verbose_name='业务对象类型')),
                ('business_key', models.CharField(max_length=100, verbose_name='业务对象标识')),
                ('dedupe_key', models.CharField(max_length=220, unique=True, verbose_name='幂等键')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='任务参数')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('succeeded', '执行成功'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='任务状态')),
                ('scheduled_at', models.DateTimeField(verbose_name='计划执行时间')),
                ('available_at', models.DateTimeField(verbose_name='下次可执行时间')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='已执行次数')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='最大执行次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='最近开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '计划任务',
                'verbose_name_plural': '计划任务',
                'db_table': 'scheduled_task',
                'ordering': ('-scheduled_at', '-id'),
                'indexes': [models.Index(fields=['status', 'available_at'], name='task_status_available_idx'), models.Index(fields=['task_type', 'status', 'scheduled_at'], name='task_type_status_sched_idx'), models.Index(fields=['business_type', 'business_key'], name='task_business_key_idx')],
            },
        ),
    ]
