# Generated by Django 5.2.17 on 2026-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcenter', '0002_alter_scheduledtask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('provider_order_payment_expiry', '达人订单支付超时'), ('provider_acceptance_timeout', '达人接单超时'), ('provider_order_confirmation_timeout', '达人订单确认超时'), ('provider_order_settlement', '达人订单资金结算')], max_length=64, verbose_name='任务类型'),
        ),
    ]
