# Generated by Django 5.2.17 on 2026-08-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('city_name', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='GCJ-02经度')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='GCJ-02纬度')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'user_address',
                'ordering': ('-is_default', '-updated_at'),
                'indexes': [models.Index(fields=['user', '-updated_at'], name='user_addres_user_id_b2dcbe_idx')],
            },
        ),
    ]
