# Generated by Django 5.2.17 on 2026-08-16 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('provider_name_snapshot', models.CharField(max_length=30, verbose_name='达人名称快照')),
                ('service_name_snapshot', models.CharField(max_length=30, verbose_name='服务名称快照')),
                ('billing_type_snapshot', models.CharField(choices=[('hourly', '按小时'), ('per_session', '按次')], max_length=16, verbose_name='计费方式快照')),
                ('unit_price_amount', models.PositiveBigIntegerField(verbose_name='单价快照（分）')),
                ('starts_at', models.DateTimeField(verbose_name='服务开始时间')),
                ('ends_at', models.DateTimeField(verbose_name='服务结束时间')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='服务时长（分钟）')),
                ('map_source', models.CharField(default='amap', max_length=16, verbose_name='地图来源')),
                ('meeting_address', models.CharField(max_length=255, verbose_name='集合地点')),
                ('source_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='原始GCJ-02经度')),
                ('source_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='原始GCJ-02纬度')),
                ('route_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='单程路线距离（公里）')),
                ('contact_name', models.CharField(max_length=30, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('service_fee_amount', models.PositiveBigIntegerField(verbose_name='服务费（分）')),
                ('transport_fee_amount', models.PositiveBigIntegerField(default=0, verbose_name='往返交通费（分）')),
                ('other_fee_amount', models.PositiveBigIntegerField(default=0, verbose_name='其他费用（分）')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='优惠金额（分）')),
                ('payable_amount', models.PositiveBigIntegerField(verbose_name='应付金额（分）')),
                ('pricing_snapshot', models.JSONField(default=dict, verbose_name='计价规则快照')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('pending_acceptance', '待接单'), ('pending_support', '待客服处理'), ('pending_service', '待服务'), ('departed', '已出发'), ('in_service', '服务中'), ('pending_confirmation', '待确认'), ('pending_review', '待评价'), ('completed', '已完成'), ('cancelled', '已取消'), ('after_sales', '售后中'), ('refunded', '已退款')], default='pending_payment', max_length=24, verbose_name='订单状态')),
                ('payment_expires_at', models.DateTimeField(verbose_name='支付及档期锁定截止时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_orders', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='providers.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='providers.providerservice')),
            ],
            options={
                'verbose_name': '达人订单',
                'verbose_name_plural': '达人订单',
                'db_table': 'provider_order',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer', 'status', '-created_at'], name='provider_or_custome_2814de_idx'), models.Index(fields=['provider', 'starts_at', 'ends_at'], name='provider_or_provide_d71fa8_idx'), models.Index(fields=['status', 'payment_expires_at'], name='provider_or_status_91fb94_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='order_end_after_start'), models.CheckConstraint(condition=models.Q(('payable_amount__gte', 0)), name='order_payable_nonnegative')],
            },
        ),
    ]
