# Generated by Django 5.2.17 on 2026-09-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_providerorder_rejection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorder',
            name='acceptance_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='达人接单截止时间'),
        ),
    ]
