# Generated by Django 5.2.17 on 2026-09-01 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediafiles", "0001_initial"),
        ("orders", "0007_providerorder_acceptance_expires_at"),
        ("providers", "0011_provider_live_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="providerorder",
            name="auto_confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="系统自动确认时间"),
        ),
        migrations.AddField(
            model_name="providerorder",
            name="confirmation_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="用户确认截止时间"),
        ),
        migrations.AddIndex(
            model_name="providerorder",
            index=models.Index(
                fields=["status", "confirmation_expires_at"], name="provider_or_status_c94a87_idx"
            ),
        ),
    ]
