# Generated by Django 5.2.17 on 2026-09-02 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_providerorder_auto_confirmed_at_and_more'),
        ('providers', '0011_provider_live_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='评分')),
                ('content', models.CharField(blank=True, max_length=500, verbose_name='评价内容')),
                ('is_visible', models.BooleanField(default=True, verbose_name='公开显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='orders.providerorder', verbose_name='达人订单')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_reviews', to='providers.providerprofile', verbose_name='达人')),
            ],
            options={
                'verbose_name': '达人订单评价',
                'verbose_name_plural': '达人订单评价',
                'db_table': 'provider_order_review',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'is_visible', '-created_at'], name='provider_or_provide_91fd0b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='provider_review_rating_between_1_5')],
            },
        ),
    ]
