# Generated by Django 5.2.17 on 2026-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
        ('orders', '0009_providerorderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorderreview',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='provider_order_reviews', to='mediafiles.mediaasset', verbose_name='评价图片'),
        ),
        migrations.AddField(
            model_name='providerorderreview',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名评价'),
        ),
    ]
