# Generated by Django 5.2.17 on 2026-09-04 23:18

import django.db.models.deletion
import django.db.models.expressions
import orders.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_provider_order_payments(apps, schema_editor):
    ProviderOrder = apps.get_model('orders', 'ProviderOrder')
    ProviderOrderPaymentOrder = apps.get_model('orders', 'ProviderOrderPaymentOrder')
    rows = []
    for order in ProviderOrder.objects.all().iterator(chunk_size=500):
        if order.paid_at:
            status = 'refunded' if order.status == 'refunded' else 'paid'
            channel = 'mock_wechat'
            gateway_trade_no = f'LEGACY-{order.order_no}'
        elif order.status == 'cancelled':
            status = 'closed'
            channel = 'unselected'
            gateway_trade_no = ''
        else:
            status = 'pending_payment'
            channel = 'unselected'
            gateway_trade_no = ''
        rows.append(ProviderOrderPaymentOrder(
            order_id=order.pk,
            payer_id=order.customer_id,
            service_fee_amount=order.service_fee_amount,
            transport_fee_amount=order.transport_fee_amount,
            other_fee_amount=order.other_fee_amount,
            discount_amount=order.discount_amount,
            payable_amount=order.payable_amount,
            pricing_snapshot=order.pricing_snapshot,
            channel=channel,
            status=status,
            gateway_trade_no=gateway_trade_no,
            expires_at=order.payment_expires_at,
            paid_at=order.paid_at,
            closed_at=order.cancelled_at if status == 'closed' else None,
        ))
        if len(rows) >= 500:
            ProviderOrderPaymentOrder.objects.bulk_create(rows)
            rows = []
    if rows:
        ProviderOrderPaymentOrder.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_providerorderreview_images_and_more'),
        ('providers', '0012_servicecategory_platform_commission_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrderPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(default=orders.models.generate_provider_payment_no, editable=False, max_length=24, unique=True, verbose_name='支付单号')),
                ('service_fee_amount', models.PositiveBigIntegerField(verbose_name='服务费（分）')),
                ('transport_fee_amount', models.PositiveBigIntegerField(verbose_name='交通费（分）')),
                ('other_fee_amount', models.PositiveBigIntegerField(verbose_name='其他费用（分）')),
                ('discount_amount', models.PositiveBigIntegerField(verbose_name='优惠金额（分）')),
                ('payable_amount', models.PositiveBigIntegerField(verbose_name='应付金额（分）')),
                ('pricing_snapshot', models.JSONField(default=dict, verbose_name='计价规则快照')),
                ('channel', models.CharField(choices=[('unselected', '待选择'), ('mock_wechat', '模拟微信支付'), ('mock_alipay', '模拟支付宝'), ('wechat', '微信支付'), ('alipay', '支付宝')], default='unselected', max_length=20, verbose_name='支付渠道')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('closed', '已关闭'), ('partially_refunded', '部分退款'), ('refunded', '已退款')], default='pending_payment', max_length=24, verbose_name='支付状态')),
                ('gateway_trade_no', models.CharField(blank=True, max_length=64, verbose_name='渠道交易号')),
                ('expires_at', models.DateTimeField(verbose_name='支付失效时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_order', to='orders.providerorder', verbose_name='达人订单')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_order_payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='付款人')),
            ],
            options={
                'verbose_name': '达人订单支付单',
                'verbose_name_plural': '达人订单支付单',
                'db_table': 'provider_order_payment_order',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProviderOrderRefundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(default=orders.models.generate_provider_refund_no, editable=False, max_length=24, unique=True, verbose_name='退款单号')),
                ('idempotency_key', models.CharField(max_length=120, unique=True, verbose_name='幂等键')),
                ('source_type', models.CharField(choices=[('after_sales', '退款售后'), ('admin', '后台退款'), ('system', '系统退款')], max_length=20, verbose_name='退款来源')),
                ('source_reference', models.CharField(max_length=64, verbose_name='来源单号')),
                ('service_fee_refund_amount', models.PositiveBigIntegerField(verbose_name='服务费退款（分）')),
                ('transport_fee_refund_amount', models.PositiveBigIntegerField(verbose_name='交通费退款（分）')),
                ('other_fee_refund_amount', models.PositiveBigIntegerField(verbose_name='其他费用退款（分）')),
                ('refund_amount', models.PositiveBigIntegerField(verbose_name='退款总额（分）')),
                ('allocation_snapshot', models.JSONField(default=dict, verbose_name='退款分配快照')),
                ('status', models.CharField(choices=[('pending', '待退款'), ('processing', '退款处理中'), ('succeeded', '退款成功'), ('failed', '退款失败')], default='pending', max_length=20, verbose_name='退款状态')),
                ('gateway_refund_no', models.CharField(blank=True, max_length=64, verbose_name='渠道退款号')),
                ('reason', models.CharField(max_length=1000, verbose_name='退款原因')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间')),
                ('failure_reason', models.CharField(blank=True, max_length=1000, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_order_refund_orders', to=settings.AUTH_USER_MODEL, verbose_name='退款用户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_provider_order_refunds', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_orders', to='orders.providerorder', verbose_name='达人订单')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_orders', to='orders.providerorderpaymentorder', verbose_name='原支付单')),
            ],
            options={
                'verbose_name': '达人订单退款单',
                'verbose_name_plural': '达人订单退款单',
                'db_table': 'provider_order_refund_order',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProviderOrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_no', models.CharField(default=orders.models.generate_provider_settlement_no, editable=False, max_length=24, unique=True, verbose_name='结算单号')),
                ('paid_amount', models.PositiveBigIntegerField(verbose_name='实付金额（分）')),
                ('refunded_amount', models.PositiveBigIntegerField(default=0, verbose_name='已退款金额（分）')),
                ('net_service_fee_amount', models.PositiveBigIntegerField(verbose_name='净服务费（分）')),
                ('net_transport_fee_amount', models.PositiveBigIntegerField(verbose_name='净交通费（分）')),
                ('net_other_fee_amount', models.PositiveBigIntegerField(verbose_name='净其他费用（分）')),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='平台抽成比例（%）')),
                ('platform_commission_amount', models.PositiveBigIntegerField(verbose_name='平台抽成（分）')),
                ('provider_service_income_amount', models.PositiveBigIntegerField(verbose_name='达人服务收入（分）')),
                ('provider_settlement_amount', models.PositiveBigIntegerField(verbose_name='达人结算金额（分）')),
                ('status', models.CharField(choices=[('risk_frozen', '风险冻结中'), ('dispute_frozen', '争议冻结中'), ('settled', '已结算入账'), ('cancelled', '已取消')], default='risk_frozen', max_length=24, verbose_name='结算状态')),
                ('frozen_at', models.DateTimeField(verbose_name='冻结开始时间')),
                ('freeze_until', models.DateTimeField(verbose_name='冻结截止时间')),
                ('dispute_reason', models.CharField(blank=True, max_length=1000, verbose_name='争议冻结原因')),
                ('calculation_snapshot', models.JSONField(default=dict, verbose_name='结算计算快照')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算入账时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='orders.providerorder', verbose_name='达人订单')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_settlements', to='providers.providerprofile', verbose_name='结算达人')),
            ],
            options={
                'verbose_name': '达人订单结算单',
                'verbose_name_plural': '达人订单结算单',
                'db_table': 'provider_order_settlement',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='providerorderpaymentorder',
            index=models.Index(fields=['payer', 'status', '-created_at'], name='provider_pay_payer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='providerorderpaymentorder',
            index=models.Index(fields=['status', 'expires_at'], name='provider_pay_status_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerorderpaymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('payable_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('service_fee_amount'), '+', models.F('transport_fee_amount')), '+', models.F('other_fee_amount')), '-', models.F('discount_amount')))), name='provider_payment_amount_matches'),
        ),
        migrations.AddConstraint(
            model_name='providerorderpaymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_trade_no', ''), _negated=True), fields=('gateway_trade_no',), name='uniq_provider_gateway_trade_no'),
        ),
        migrations.AddIndex(
            model_name='providerorderrefundorder',
            index=models.Index(fields=['order', 'status', '-created_at'], name='provider_ref_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='providerorderrefundorder',
            index=models.Index(fields=['status', 'requested_at'], name='provider_ref_status_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerorderrefundorder',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('service_fee_refund_amount'), '+', models.F('transport_fee_refund_amount')), '+', models.F('other_fee_refund_amount')))), name='provider_refund_amount_matches'),
        ),
        migrations.AddConstraint(
            model_name='providerorderrefundorder',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gt', 0)), name='provider_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='providerorderrefundorder',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_refund_no', ''), _negated=True), fields=('gateway_refund_no',), name='uniq_provider_gateway_refund_no'),
        ),
        migrations.AddIndex(
            model_name='providerordersettlement',
            index=models.Index(fields=['status', 'freeze_until'], name='provider_set_status_freeze_idx'),
        ),
        migrations.AddIndex(
            model_name='providerordersettlement',
            index=models.Index(fields=['provider', 'status', '-created_at'], name='provider_set_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerordersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('paid_amount'))), name='provider_set_refunded_lte_paid'),
        ),
        migrations.AddConstraint(
            model_name='providerordersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('provider_settlement_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('provider_service_income_amount'), '+', models.F('net_transport_fee_amount')), '+', models.F('net_other_fee_amount')))), name='provider_settlement_amount_matches'),
        ),
        migrations.AddConstraint(
            model_name='providerordersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('refunded_amount'), '+', models.F('platform_commission_amount')), '+', models.F('provider_settlement_amount')))), name='provider_settlement_balance_matches'),
        ),
        migrations.AddConstraint(
            model_name='providerordersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('freeze_until__gte', models.F('frozen_at'))), name='provider_settlement_freeze_valid'),
        ),
        migrations.RunPython(backfill_provider_order_payments, migrations.RunPython.noop),
    ]
