# Generated by Django 5.2.17 on 2026-09-22 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_reviews(apps, schema_editor):
    review_model = apps.get_model('orders', 'ProviderOrderReview')
    review_model.objects.filter(audit_status='pending').update(audit_status='approved')


def reset_existing_reviews(apps, schema_editor):
    review_model = apps.get_model('orders', 'ProviderOrderReview')
    review_model.objects.filter(audit_status='approved').update(audit_status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
        ('orders', '0018_settlement_copy_matches_ledger'),
        ('providers', '0015_configure_initial_service_price_ranges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorderreview',
            name='audit_rejection_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='审核驳回原因'),
        ),
        migrations.AddField(
            model_name='providerorderreview',
            name='audit_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核驳回')], default='pending', max_length=16, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='providerorderreview',
            name='audited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='providerorderreview',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audited_provider_order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.RunPython(approve_existing_reviews, reset_existing_reviews),
        migrations.AddIndex(
            model_name='providerorderreview',
            index=models.Index(fields=['audit_status', '-created_at'], name='provider_or_audit_s_3352fc_idx'),
        ),
    ]
