# Generated by Django 5.2.17 on 2026-09-23 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_providerorderreview_audit_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorder',
            name='review_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='评价截止时间'),
        ),
        migrations.AddField(
            model_name='providerorderreview',
            name='is_auto_generated',
            field=models.BooleanField(default=False, verbose_name='系统默认好评'),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('face_amount', models.PositiveIntegerField(verbose_name='面额（分）')),
                ('min_order_amount', models.PositiveIntegerField(verbose_name='订单使用门槛（分）')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('status', models.CharField(choices=[('available', '可使用'), ('reserved', '订单占用中'), ('used', '已使用')], default='available', max_length=12)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_coupons', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('reserved_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_coupon', to='orders.providerorder')),
            ],
            options={
                'db_table': 'user_coupon',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['owner', 'status', 'expires_at'], name='user_coupon_owner_i_50ec0a_idx')],
            },
        ),
    ]
