# Generated by Django 5.2.17 on 2026-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_backfill_pending_review_deadlines'),
        ('providers', '0016_providerprofile_commission_reset_period_override_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providerordersettlement',
            index=models.Index(fields=['provider', 'status', 'frozen_at'], name='provider_set_turnover_idx'),
        ),
    ]
