# Generated by Django 5.2.17 on 2026-09-25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_providerordersettlement_provider_set_turnover_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=80, verbose_name="优惠券名称")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="使用说明")),
                ("face_amount", models.PositiveIntegerField(verbose_name="面额（分）")),
                ("min_order_amount", models.PositiveIntegerField(default=0, verbose_name="订单使用门槛（分）")),
                ("valid_days", models.PositiveSmallIntegerField(default=30, verbose_name="领取后有效天数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_coupon_templates", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="updated_coupon_templates", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "coupon_template",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="revoke_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="revoked_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="revoked_coupons", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="template",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="coupons", to="orders.coupontemplate"),
        ),
        migrations.AlterField(
            model_name="usercoupon",
            name="status",
            field=models.CharField(choices=[("available", "可使用"), ("reserved", "订单占用中"), ("used", "已使用"), ("revoked", "已撤销")], default="available", max_length=12),
        ),
    ]
