# Generated by Django 5.2.17 on 2026-10-07 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0004_mediaasset_duration_ms'),
        ('orders', '0033_coupon_issue_batches'),
        ('providers', '0023_first_order_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorder',
            name='completion_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='未提交完成核查时间'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='departure_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='未出发自动取消截止时间'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='departure_timed_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='未出发超时取消时间'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='start_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='未开始服务核查时间'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='timeout_credit_points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='超时实际扣分'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='timeout_credit_reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='超时扣分申诉撤销时间'),
        ),
        migrations.AddIndex(
            model_name='providerorder',
            index=models.Index(fields=['status', 'departure_deadline_at'], name='order_departure_deadline_idx'),
        ),
    ]
