# Generated by Django 5.2.17 on 2026-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_early_termination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorder',
            name='arrival_confirmation',
            field=models.JSONField(blank=True, default=dict, verbose_name='首次到场证据快照'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次有效到场时间'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='cancellation_policy',
            field=models.JSONField(blank=True, default=dict, verbose_name='下单取消规则及同意记录'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='cancellation_record',
            field=models.JSONField(blank=True, default=dict, verbose_name='取消费用裁定快照'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='customer_wait',
            field=models.JSONField(blank=True, default=dict, verbose_name='失联等待记录'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='customer_wait_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='用户失联等待截止'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='provider_last_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近发起联系时间'),
        ),
        migrations.AddField(
            model_name='providerorder',
            name='transport_mode',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='下单出行方式'),
        ),
    ]
