# Generated by Django 5.2.17 on 2026-10-10 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0004_mediaasset_duration_ms'),
        ('orders', '0036_providerorder_arrival_confirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='name_snapshot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='CouponCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('stock', models.PositiveIntegerField()),
                ('issued_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已上架'), ('offline', '已下架')], default='draft', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_campaigns', to='mediafiles.mediaasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_coupon_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_campaigns', to='orders.coupontemplate')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_coupon_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_claim_campaign',
                'ordering': ('sort_order', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CouponCampaignClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='orders.couponcampaign')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_claim', to='orders.usercoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_campaign_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_campaign_claim',
            },
        ),
        migrations.AddIndex(
            model_name='couponcampaign',
            index=models.Index(fields=['status', 'ends_at'], name='claim_campaign_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', models.F('issued_count'))), name='claim_campaign_stock_gte_issued'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gt', 0)), name='claim_campaign_positive_stock'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='claim_campaign_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaignclaim',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='unique_campaign_claim_user'),
        ),
    ]
