# Generated by Django 5.2.17 on 2026-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='event_type',
            field=models.CharField(choices=[('support_reply', '客服回复'), ('support_result', '工单处理结果'), ('support_review_result', '工单复核结果'), ('order_payment_success', '订单支付成功'), ('order_accepted', '达人已接单'), ('order_pending_support', '订单转客服处理'), ('order_departed', '达人已出发'), ('order_started', '服务已开始'), ('order_completion_submitted', '达人提交完成'), ('order_auto_confirmed', '订单自动确认'), ('order_after_sales_started', '订单售后处理中'), ('order_after_sales_result', '订单售后结果'), ('order_refund_completed', '订单退款完成'), ('provider_order_settled', '达人订单结算完成'), ('activity_publish_submitted', '活动提交审核'), ('activity_review_result', '活动审核结果'), ('activity_signup_success', '活动报名成功'), ('activity_formed', '活动已成局'), ('activity_refund_completed', '活动退款完成'), ('activity_cancelled', '活动已取消'), ('activity_failed_to_form', '活动未成局'), ('activity_started', '活动已开始'), ('activity_completed', '活动已结束'), ('activity_after_sales_result', '活动售后结果'), ('activity_settled', '活动结算完成'), ('provider_application_result', '达人申请审核结果'), ('provider_status_changed', '达人资格变更'), ('provider_credit_changed', '达人信用分变更')], max_length=40, verbose_name='事件类型'),
        ),
    ]
