# Generated by Django 5.2.17 on 2026-08-22 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0004_alter_activitypublishorder_activity'),
        ('providers', '0003_alter_providerprofile_map_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('provider', '达人'), ('activity', '活动')], max_length=16)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='activities.activity')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='providers.providerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'browsing_history',
                'ordering': ('-viewed_at', '-id'),
                'indexes': [models.Index(fields=['user', 'target_type', '-viewed_at'], name='browsing_hi_user_id_529e1f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('provider__isnull', False), ('target_type', 'provider')), models.Q(('activity__isnull', False), ('provider__isnull', True), ('target_type', 'activity')), _connector='OR'), name='history_target_matches_type'), models.UniqueConstraint(condition=models.Q(('provider__isnull', False)), fields=('user', 'provider'), name='uniq_user_provider_history'), models.UniqueConstraint(condition=models.Q(('activity__isnull', False)), fields=('user', 'activity'), name='uniq_user_activity_history')],
            },
        ),
        migrations.CreateModel(
            name='ProviderFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='providers.providerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_favorite',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='provider_fa_user_id_4e2ee6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='uniq_user_provider_favorite')],
            },
        ),
    ]
